spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/codility
    #password: Admin@123
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
